version: '3.4'

services:
  mongodb:
    image: 'mongo'
    volumes: 
      - mongo_data:/data/db
    env_file: 
      - ./env/mongo.env
  api:
    image: api
    build:
      context: src/api
      dockerfile: ./api.Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src/api/:/src/api/
      - api_node_modules:/src/api/node_modules
    env_file: 
      - ./env/api.env
    depends_on:
      - mongodb







volumes:
  mongo_data:
  api_node_modules:
